# Generated by Django 5.2.7 on 2025-11-19 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, help_text='Cole aqui o link para o formulário, vídeo, etc.', max_length=500, null=True)),
                ('pontos', models.IntegerField(default=10, help_text='Quantos pontos esta atividade vale?')),
                ('codigo_conclusao', models.CharField(blank=True, help_text='[Opcional] Se preenchido, o aluno deve digitar este código para ganhar os pontos.', max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateField(blank=True, help_text='Data limite para a atividade (opcional).', null=True)),
                ('arquivo', models.FileField(blank=True, help_text='Anexe um material de apoio, se necessário.', null=True, upload_to='atividades/')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_link', models.URLField(blank=True, help_text='Gerado automaticamente pelo sistema', max_length=255, null=True, verbose_name='Link da Planilha Google')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_acesso', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('pontos_ganhos', models.IntegerField(default=0)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.atividade')),
            ],
            options={
                'ordering': ['data_conclusao'],
            },
        ),
    ]
