# Generated by Django 5.2.7 on 2025-11-19 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='atividades_concluidas',
            field=models.ManyToManyField(blank=True, through='homepage.Conclusao', to='homepage.atividade'),
        ),
        migrations.AddField(
            model_name='conclusao',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.inscricao'),
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='turmas_matriculadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.turma'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='homepage.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='conclusao',
            unique_together={('inscricao', 'atividade')},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('aluno', 'turma')},
        ),
    ]
