# Generated by Django 5.2.7 on 2025-12-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='vale_xp',
            field=models.BooleanField(default=True, help_text='Se desmarcado, será apenas um aviso (sem botão de concluir).', verbose_name='Vale Nota/XP?'),
        ),
    ]
