# Generated by Django 5.2.7 on 2026-01-26 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_conquista_conquistaaluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conquista',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='xp_bonus',
        ),
        migrations.AddField(
            model_name='conquista',
            name='chave',
            field=models.CharField(default='temp', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conquista',
            name='imagem_arquivo',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conquistaaluno',
            name='data_conquista',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
