# Generated by Django 5.2.7 on 2026-01-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_conquista_imagem_remove_conquista_xp_bonus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conclusao',
            options={},
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='link',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='atividades_concluidas',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='atividades/'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='codigo_conclusao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, default='temp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='vale_xp',
            field=models.BooleanField(default=True),
        ),
    ]
