# Generated by Django 5.2.7 on 2026-03-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_conclusao_options_remove_atividade_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclusao',
            name='nota_atribuida',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='conclusao',
            name='ra_validado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RA Confirmado'),
        ),
        migrations.AddField(
            model_name='conclusao',
            name='voucher_bruto',
            field=models.TextField(blank=True, null=True, verbose_name='Hash do Voucher'),
        ),
        migrations.AddField(
            model_name='turma',
            name='chave_publica_pem',
            field=models.TextField(blank=True, help_text='Chave pública utilizada para validar os vouchers desta turma.', null=True, verbose_name='Chave Pública RSA (PEM)'),
        ),
    ]
